### ISSUE TITLE
Xây dựng lại bộ dữ liệu theo từng chủ đề danh mục bài học, một số câu hỏi của từng chủ đề chưa rõ ràng. Có những cách nào để hiểu rõ hơn về từng chủ đề ? 

### ISSUE THREAD

**Issue by huyle73** [huyle73/SE05-Nhom23#3]
![Screen Shot 2020-12-02 at 9 05 38 PM](https://user-images.githubusercontent.com/54856997/100882848-3b797180-34e2-11eb-959f-142f2f2fe1ff.png)

**Comment by khanhhoaa19** [comment]
Chào bạn, cảm ơn vì câu hỏi của bạn, với việc xây dựng lại bộ dữ liệu theo từng chủ đề danh mục bài học, một số câu hỏi của từng chủ đề chưa được rõ ràng và đa dạng cần sự tư vấn của mentor công ty.
