### ISSUE TITLE
Dữ liệu update như thế nào?

### ISSUE THREAD

**Issue by doduydao19** [huyle73/SE05-Nhom23#5]
Mình thấy dữ liệu thô đã được chia ra nhưng chia như vậy khi cần update nhanh thì không dc tiện cho lắm. Các bạn có hướng giải quyết nào k ?

**Comment by khanhhoaa19** [comment]
Chào bạn, với việc những dữ liệu mới, chúng mình đã dụng CSDL MySQL để update một cách nhanh chóng, thuận tiện và dễ sử dụng với ngưởi dùng

**Comment by doduydao19** [comment]
vậy giả sử mình có 100k câu hỏi và trả lời thì các bạn phân loại và đẩy vào database như thế nào ?

**Comment by khanhhoaa19** [comment]
Với 100k câu hỏi chúng mình sẽ cố gắng tạo tool gán nhãn tự động trong tương lai, cảm ơn bạn vì câu hỏi.

**Comment by huyle73** [comment]
nhóm mình có thể sử dụng bài toán text classification để phân loại các nhãn một cách tự động, cảm ơn vì sự đóng góp của 2 bạn.

**Comment by huyle73** [comment]
Chúng mình có thể sử dụng bài toán text classification.
